development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
  github_access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %> 
  devise:
    pepper: <%= ENV['DEVISE_PEPPER'] %>
    secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  
test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
  github_access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %> 
  devise:
    pepper: <%= ENV['DEVISE_PEPPER'] %>
    secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %> 
  github_access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %> 
  postgresql:
    username: <%= ENV['POSTGRESQL_USERNAME'] %>
    password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  devise:
    pepper: <%= ENV['DEVISE_PEPPER'] %>
    secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
