development:
  secret_key_base: utrncc42ugtb289u3ngt4cbbnxrifxucgt4nrijmxicgtjunrxijf09i2rxngtcb5uxinj9g2c9rijx201928409c4nug6gxg89cgt6ubnxfigc9t8hxnjutifgtutre
  github_access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %> 
  devise_secret_key: 12934ec63edsfgdi3trergnr23rfeferergerge23dkfgdfngdfgdfgd11a7fecd5ce8822bc3b800b5b19693e7abd7237c4d4a28c818f68733c3183ee557c675c2
  
test:
  secret_key_base: 234erimnnunimocj2h3vu84hrinjxc24xnju9i1c0934xiomxrcngtu4h9jxi02omzkx9jcgintmoxfcjgnmofxrgk09cjt5inmxcgtu9n9nximfgcntu9ximorcgtca
  github_access_token: 456adasdfddadsfadsdfdasfdsadffdasfadsfda
  devise_secret_key: 12934ec63edsfgdi3trergnr23rfeferergerge23dkfgdfngdfgdfgd11a7fecd5ce8822bc3b800b5b19693e7abd7237c4d4a28c818f68733c3183ee557c675c2

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  github_access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %> 
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %> 
